#!/bin/sh
#
# script to update and rotate the AIDE database files and
# create a detached GPG signature to verify the database file
#
# written by Vincent Danen <vdanen-at-annvix.org>
#
# $Id$

distro="Annvix"
gpg="/usr/bin/gpg"
aide="/usr/sbin/aide"
fname="aide-`hostname`-`date +%Y%m%d-%H%M%S`"
host="`hostname`"

if [ ! -d /var/lib/aide ]; then
    echo "The AIDE database directory /var/lib/aide does not exist!"
    exit 1
fi

if [ ! -d /var/lib/aide/reports ]; then
    echo "Creating /var/lib/aide/reports to store reports"
    mkdir /var/lib/aide/reports && chmod 0700 /var/lib/aide/reports
fi

pushd /var/lib/aide >/dev/null

# copy the old database
if [ -f aide.db ]; then
    newfile="${fname}.db"
    if [ -f aide.db.sig ]; then
        # do an integrity check
	${gpg} --verify aide.db.sig
	if [ "$?" == "1" ]; then
	    echo "************************************************************"
	    echo "GPG signature FAILED!  Your database has been tampered with!"
	    echo "************************************************************"
	    exit 1
	fi
    else
        echo "************************************************************"
        echo "No GPG signature file found!  Your system may be compromised"
        echo "or incorrectly configured!  Please read man afterboot for"
        echo "more information on how to correctly configure AIDE on"
        echo "${distro}!"
        echo "************************************************************"
        exit 1
    fi
    cp -a aide.db ${newfile} 
    ${aide} --update -B "database=file:/var/lib/aide/${newfile}" -B "database_out=file:/var/lib/aide/aide.db" \
        -B "report_url=file:/var/lib/aide/reports/${fname}.report"
    # create the signature file
    [[ -f aide.db.sig ]] && rm -f aide.db.sig
    echo ""
    read -s -e -p "Enter your AIDE gpg password: " gpgpass
    echo ${gpgpass} | ${gpg} -u aide@${host} --passphrase-fd stdin --no-tty --detach-sign aide.db
    echo ""
    if [ "$?" == "1" ]; then
	echo "FATAL:  Error occurred when creating the signature file!"
	exit 1
    fi
    gzip -9f ${newfile}
else
    echo "The AIDE database does not exist, can't update!"
    exit 1
fi

popd >/dev/null

exit 0
