#!/bin/sh
#
# Annvix script to remove supervised service via rpm scriptlet
#
# Copyright (c) 2005 Vincent Danen <vdanen@annvix.org>
#
# $Id$

if [ $# != 3 ]; then
    echo "usage: ${0} <pkg name> <number installed> <service name>" 1>&2
    exit 1
fi

pkg="${1}"				# name of the package
num="${2}"				# number of packages installed
srv="${3}"				# name of the service

if [ ${num} = 0 ]; then
    if [ -d /service/${srv} ]; then
	/usr/sbin/srv --down ${srv} >/dev/null 2>&1 || :
	/usr/sbin/srv --del ${srv}
	if [ -f /var/lock/subsys/apparmor ]; then
	    /sbin/service apparmor reload >/dev/null 2>&1 || :
	fi
    fi
fi

# del-srv ends here
