
PTREE=/usr/local/ports

checkout:
	CVSROOT=:pserver:anonymous@cvs.opensls.org:/cvsroot cvs co ports

update:
	CVSROOT=:pserver:anonymous@cvs.opensls.org:/cvsroot cvs update ports

urpmi:
	urpmi.addmedia ports file:/$(PTREE)/packages with ./hdlist.cz

hdlist:
	cd $(PTREE)/packages
	genhdlist .
