#
# spec file for package findutils
#
# Package for the Annvix Linux distribution: http://annvix.org/
#
# Please submit bugfixes or comments via http://bugs.annvix.org/
#
# $Id$

%define revision	$Rev$
%define name		findutils
%define version		4.2.27
%define release		%_revrel

Summary:	The GNU versions of find utilities (find, xargs, and locate)
Name:		%{name}
Version:	%{version}
Release:	%{release}
License:	GPL
Group:		File Tools
URL:		http://www.gnu.org/software/findutils/findutils.html
Source0:	ftp://ftp.gnu.org/gnu/findutils/findutils-%{version}.tar.gz
Source1:	ftp://ftp.gnu.org/gnu/findutils/findutils-%{version}.tar.gz.sig
Patch0:		findutils-4.2.15-no-locate.patch

BuildRoot:	%{_buildroot}/%{name}-%{version}
BuildRequires:	automake1.8
# for autoreconf -> autopoint
BuildRequires:	cvs
BuildRequires:	gettext-devel

Requires(post):	info-install
Requires(preun): info-install

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a filename pattern).   The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).


%package doc
Summary:	Documentation for %{name}
Group:		Documentation

%description doc
This package contains the documentation for %{name}.


%prep
%setup -q
%patch0 -p1 -b .no-locate

# needed by P0
ACLOCAL=aclocal-1.9 AUTOMAKE=automake-1.9 autoreconf --force --install


%build
%configure2_5x
%make


%install
[ -n "%{buildroot}" -a "%{buildroot}" != / ] && rm -rf %{buildroot}
%makeinstall_std

mkdir %{buildroot}/bin
mv %{buildroot}%{_bindir}/find %{buildroot}/bin
ln -sf ../../bin/find %{buildroot}%{_bindir}/find

%kill_lang %{name}
%find_lang %{name}


%post
%_install_info find.info

%preun
%_remove_install_info find.info


%clean
[ -n "%{buildroot}" -a "%{buildroot}" != / ] && rm -rf %{buildroot}


%files -f %{name}.lang
%defattr(-,root,root)
/bin/find
%{_bindir}/find
%{_bindir}/xargs
%{_mandir}/man1/find.1*
%{_mandir}/man1/xargs.1*
%{_infodir}/find.info*

%files doc
%defattr(-,root,root)
%doc NEWS README


%changelog
* Tue Aug 15 2006 Vincent Danen <vdanen-at-build.annvix.org> 4.2.27
- spec cleanups
- remove locales

* Sat Jul 08 2006 Vincent Danen <vdanen-at-build.annvix.org> 4.2.27
- 4.2.27
- add -doc subpackage
- rebuild with gcc4
- fixed source url

* Wed Jan 11 2006 Vincent Danen <vdanen-at-build.annvix.org> 4.2.25
- Clean rebuild

* Wed Jan 04 2006 Vincent Danen <vdanen-at-build.annvix.org> 4.2.25
- Obfuscate email addresses and new tagging
- Uncompress patches

* Sun Oct 09 2005 Vincent Danen <vdanen-at-build.annvix.org> 4.2.25-1avx
- 4.2.25
- fix requires(post|preun)
- add buildreq on cvs and gettext-devel for autoreconf's call to
  autopoint (cjw)

* Fri Sep 16 2005 Vincent Danen <vdanen-at-build.annvix.org> 4.2.24-1avx
- 4.2.24
- drop old S1 (updatedb for cron)
- change description to reflect that locate isn't in this package

* Wed Aug 10 2005 Vincent Danen <vdanen-at-build.annvix.org> 4.2.17-4avx
- bootstrap build (new gcc, new glibc)

* Tue Jul 26 2005 Vincent Danen <vdanen-at-build.annvix.org> 4.2.17-3avx
- rebuild for new gcc

* Fri Jun 03 2005 Vincent Danen <vdanen-at-build.annvix.org> 4.2.17-2avx
- bootstrap build

* Sat Mar 05 2005 Vincent Danen <vdanen-at-build.annvix.org> 4.2.17-1avx
- 4.2.17
- P4: don't build locate
- remove S1 as it's not even used
- update %%configure/%%makeinstall macros; use automake1.8

* Fri Jun 25 2004 Vincent Danen <vdanen-at-build.annvix.org> 4.1.20-4avx
- Annvix build

* Thu Mar 04 2004 Vincent Danen <vdanen@opensls.org> 4.1.20-3sls
- minor spec cleanups

* Sun Nov 30 2003 Vincent Danen <vdanen@opensls.org> 4.1.20-2sls
- OpenSLS build
- tidy spec

# vim: expandtab:shiftwidth=8:tabstop=8:softtabstop=8
