#
# spec file for package module-init-tools
#
# Package for the Annvix Linux distribution: http://annvix.org/
#
# Please submit bugfixes or comments via http://bugs.annvix.org/
#
# $Id$

%define revision	$Rev$
%define name		module-init-tools
%define version		3.2.2
%define release		%_revrel

%define priority	20
%define _bindir		/bin
%define _sbindir	/sbin
%define _libdir		/lib
%define _libexecdir	/lib
%define toalternate	insmod lsmod modprobe rmmod depmod modinfo

Summary: 	Tools for managing Linux kernel modules
Name:		module-init-tools
Version:	%{version}
Release:	%{release}
License:	GPL
Group:		System/Kernel and hardware
URL:		ftp://ftp.kernel.org/pub/linux/kernel/people/rusty/modules/
Source0:	ftp://ftp.kernel.org/pub/linux/kernel/people/rusty/modules//%{name}-%{version}.tar.bz2
Source3:	modprobe.default
Source4:	modprobe.compat
Source5:	modprobe.preload
Patch1: 	module-init-tools-3.2-pre8-no-rename.patch
Patch2: 	module-init-tools-3.2-pre8-dont-break-depend.patch
Patch3:		module-init-tools-3.2-pre8-all-defaults.patch
Patch7:		module-init-tools-3.2-pre8-modprobe-default.patch
Patch8:		module-init-tools-3.2.2-generate-modprobe.conf-no-defaults.patch
Patch9:		module-init-tools-3.0-failed.unknown.symbol.patch

BuildRoot:	%{_buildroot}/%{name}-%{version}
BuildRequires:	autoconf2.5
BuildRequires:	glibc-static-devel
BuildRequires:	zlib-devel

Requires(post):	update-alternatives
Requires(postun): update-alternatives
Conflicts:	modutils < 2.4.22-10mdk
Conflicts:	devfsd < 1.3.25-31mdk


%description
This package contains a set of programs for loading, inserting, and
removing kernel modules for Linux (versions 2.5.47 and above). It
serves the same function that the "modutils" package serves for Linux
2.4.


%package doc
Summary:	Documentation for %{name}
Group:		Documentation

%description doc
This package contains the documentation for %{name}.


%prep
%setup -q
%patch1 -p1 -b .no-rename
%patch2 -p1 -b .dont-break-depend
%patch3 -p1 -b .all-defaults
%patch7 -p1 -b .modprobe-default
%patch8 -p1 -b .generate-modprobe.conf-no-defaults
%patch9 -p1 -b .failed-symb


%build
%serverbuild
%configure2_5x --enable-zlib
%make


%install
[ -n "%{buildroot}" -a "%{buildroot}" != / ] && rm -rf %{buildroot}
%makeinstall transform=

mv %{buildroot}%{_bindir}/lsmod %{buildroot}%{_sbindir}

pushd %{buildroot}%{_sbindir} && {
    for i in %{toalternate};do
        mv $i $i-25
    done
} && popd

rm -rf %{buildroot}/%{_mandir}
for n in 5 8;do
    install -d %{buildroot}/%{_mandir}/man$n/
    for i in *.$n;do
        [[ $n == 8 ]] && ext="-25" || ext=""
        install -m644 $i %{buildroot}/%{_mandir}/man${n}/${i%%.*}${ext}.$n
    done
done

pushd %{buildroot}%{_sbindir} && {
%ifnarch %{ix86}
    mv insmod.static insmod.static-25
%else
    rm -f insmod.static
%endif
} && popd

install -d -m755 %{buildroot}%{_sysconfdir}/
touch %{buildroot}%{_sysconfdir}/modprobe.conf
install -m 644 %{SOURCE5} %{buildroot}%{_sysconfdir}
install -d -m755 %{buildroot}%{_sysconfdir}/modprobe.d/

install -d -m755 %{buildroot}%{_libdir}/module-init-tools
install -m 644 %{SOURCE3} %{buildroot}%{_libdir}/module-init-tools
install -m 644 %{SOURCE4} %{buildroot}%{_libdir}/module-init-tools


%post
for i in %{toalternate};do
    update-alternatives --install %{_sbindir}/$i $i %{_sbindir}/$i-25 %{priority}
    update-alternatives --install \
    %{_mandir}/man8/$i.8%{_extension} man-$i %{_mandir}/man8/$i-25.8%{_extension} %{priority}
    [ -e %{_sbindir}/$i ] || update-alternatives --auto $i
    [ -e %{_mandir}/$i.8%{_extension} ] || update-alternatives --auto man-$i
done

if [ ! -s %{_sysconfdir}/modprobe.conf ]; then
    MODPROBE_CONF=%{_sysconfdir}/modprobe.conf
elif [ -e %{_sysconfdir}/modprobe.conf.rpmnew ]; then
    MODPROBE_CONF=%{_sysconfdir}/modprobe.conf.rpmnew
fi

if [ -s %{_sysconfdir}/modules.conf -a -n "$MODPROBE_CONF" ]; then
    echo '# This file is autogenerated from %{_sysconfdir}/modules.conf using generate-modprobe.conf command' >> $MODPROBE_CONF
    echo >> $MODPROBE_CONF
    %{_sbindir}/generate-modprobe.conf >> $MODPROBE_CONF 2> /dev/null
fi

if [ -s %{_sysconfdir}/modprobe.conf ]; then
    perl -pi -e 's/(^\s*include\s.*modprobe\.(default|compat).*)/# This file is now included automatically by modprobe\n# $1/' %{_sysconfdir}/modprobe.conf
fi


%postun
for i in %{toalternate};do
    if [ ! -f %{_sbindir}/$i-25 ]; then
        update-alternatives --remove $i %{_sbindir}/$i
    fi
    [ -e %{_sbindir}/$i ] || update-alternatives --auto $i

    if [ ! -f %{_mandir}/man8/$i-25.8%{_extension} ]; then
        update-alternatives --remove man-$i %{_mandir}/man8/$i.8%{_extension}
    fi
    [ -e %{_mandir}/man8/$i.8%{_extension} ] || update-alternatives --auto man-$i
done


%clean
[ -n "%{buildroot}" -a "%{buildroot}" != / ] && rm -rf %{buildroot}


%files
%defattr(-,root,root)
%config(noreplace) %{_sysconfdir}/modprobe.conf
%config(noreplace) %{_sysconfdir}/modprobe.preload
%dir %{_sysconfdir}/modprobe.d/
%dir %{_libdir}/module-init-tools
%{_libdir}/module-init-tools/*
%{_sbindir}/generate-modprobe.conf
%{_sbindir}/*25
%{_mandir}/*/*

%files doc
%defattr(-,root,root)
%doc AUTHORS COPYING ChangeLog NEWS README 
%doc TODO stress_modules.sh


%changelog
* Sun Jul 23 2006 Vincent Danen <vdanen-at-build.annvix.org> 3.2.2
- add -doc subpackage
- requires packages, not files

* Mon Apr 17 2006 Vincent Danen <vdanen-at-build.annvix.org> 3.2.2
- first Annvix package for the 2.6 kernel

# vim: expandtab:shiftwidth=8:tabstop=8:softtabstop=8
