#!/bin/sh
# LSB compliant init functions

# source standard Mandrake init functions
. /etc/init.d/functions

start_daemon() {
    # Start daemons.
    gprintf "Starting %s: " $1
    daemon $1
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        touch /var/lock/subsys/$1
    fi
    echo
    return $RETVAL
}

# killproc is handled by the normal init.d/functions

# pidofproc is handled by the normal init.d/functions

log_success_msg() {
    success
}

log_failure_msg() {
    failure
}

log_warning_msg() {
    echo_warning
}


