#!/bin/bash
PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# this runs amd supervised

. /usr/share/srv/functions

checkdepends portmap

if [ ! -f /etc/amd.conf ]; then
    echo "/etc/amd.conf doesn't exist and is required to run amd!"
    godown
fi

if [ -f /etc/sysconfig/amd ] ; then
    . /etc/sysconfig/amd
else
    ADIR="/.automount"
    MOUNTPTS="-a /net"
    AMDOPTS=""
fi

exec /usr/sbin/amd -D nodaemon -F /etc/amd.conf $AMDOPTS $OPTIONS $MOUNTPTS 2>&1
