#!/bin/bash
# Emulate the jdk java command using gcj
# (c) 2002 Bernhard Rosenkraenzer <bero@bero.org>
LIBGCJ_ZIP_FILE=/usr/share/java/libgcj-@GCJ_VERSION@.jar
if [ -n "$CLASSPATH" ]; then
        clp="$CLASSPATH:$LIBGCJ_ZIP_FILE"
else
        clp="$LIBGCJ_ZIP_FILE"
fi
unset HAVE_APPNAME || :
while [ "$#" != 0 ]; do
        if [ "$1" = "-version" ]; then
                echo 'java version "@JDK_VERSION@"' 1>&2
                gij --version 1>&2
                exit 0
        elif [ "$1" = "-showversion" ]; then
                echo 'java version "@JDK_VERSION@"' 1>&2
                gij --version 1>&2
        elif [ "$1" = "-classpath" -o "$1" = "-cp" ]; then
                shift
                clp=`echo $1 | sed "s~.*/lib/rt.jar~$LIBGCJ_ZIP_FILE~"`
	elif [ "`echo $1 |cut -b1-2`" = "-D" ]; then
		if [ "`echo $1 |cut -b1-20`" = "-Djava.library.path=" ]; then
			export LD_LIBRARY_PATH=`echo $1 |cut -b21-`:$LD_LIBRARY_PATH
		fi
		params="$params \"`echo $1 |sed -e 's,",\\\\",g'`\""
        elif [ "`echo $1 |cut -b1`" = "-" ]; then
                # Yuck. Unknown parameter. Let's pretend nothing happened.
                echo "Warning: $1 not understood. Ignoring." >&2
        else
		if [ -n "$HAVE_APPNAME" ]; then
			params="$params \"`echo $1 |sed -e 's,",\\\\",g'`\""
		else
			params="$params \"`echo $1 |sed -e 's,",\\\\",g;s,/,.,g'`\""
			HAVE_APPNAME=yes
		fi
        fi
        shift
done
if ! echo $clp |grep -q $LIBGCJ_ZIP_FILE; then
	# We NEED this
	clp="$clp:$LIBGCJ_ZIP_FILE"
fi
export CLASSPATH="$clp"
eval set -- $params "$@"
exec gij "$@"
